//! Golden-reference comparison against R2-Gaussian's cone-beam
//! rasterizer (CUDA), generated by `test_cases/generate_reference.py` in
//! the `R2Gaussian` pixi env.

use brush_render::camera::Camera;
use brush_render::kernels::camera_model::CameraModel;
use brush_xray::{XRaySplats, render_xray_forward};
use burn::tensor::{Device, Tensor, TensorData};
use safetensors::SafeTensors;

const REFERENCE: &[u8] = include_bytes!("../test_cases/r2_xray_reference.safetensors");

fn f32_from_u8(data: &[u8]) -> Vec<f32> {
    data.chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect()
}

fn read_tensor<const D: usize>(
    tensors: &SafeTensors,
    name: &str,
    device: &Device,
) -> Tensor<D> {
    let t = tensors.tensor(name).expect(name);
    assert_eq!(t.dtype(), safetensors::Dtype::F32, "{name} dtype");
    Tensor::from_data(TensorData::new::<f32, _>(f32_from_u8(t.data()), t.shape()), device)
}

fn read_f32(tensors: &SafeTensors, name: &str) -> Vec<f32> {
    let t = tensors.tensor(name).expect(name);
    f32_from_u8(t.data())
}

#[tokio::test]
async fn matches_r2_cone_beam_forward() {
    let device: Device = brush_cube::test_helpers::test_device().await.into();
    let tensors = SafeTensors::deserialize(REFERENCE).expect("deserialize reference");

    let means = read_tensor::<2>(&tensors, "means", &device);
    let log_scales = read_tensor::<2>(&tensors, "log_scales", &device);
    let quats = read_tensor::<2>(&tensors, "quats", &device);
    let raw_opac = read_tensor::<1>(&tensors, "raw_opac", &device);
    let splats = XRaySplats::from_parts(means, quats, log_scales, raw_opac);

    let cam_pos = read_f32(&tensors, "cam_pos");
    let fov_x = read_f32(&tensors, "fov_x")[0] as f64;
    let fov_y = read_f32(&tensors, "fov_y")[0] as f64;
    let cam = Camera::new(
        glam::vec3(cam_pos[0], cam_pos[1], cam_pos[2]),
        glam::Quat::IDENTITY,
        fov_x,
        fov_y,
        glam::vec2(0.5, 0.5),
        CameraModel::Pinhole,
    );
    let img_size = glam::uvec2(64, 64);

    let proj = render_xray_forward(&splats, &cam, img_size, 1.0).await;
    let proj = proj.to_data_async().await.expect("readback");
    let ours = proj.as_slice::<f32>().expect("f32");

    let reference = read_f32(&tensors, "out_img");
    assert_eq!(reference.len(), 64 * 64, "reference image size");

    // Report per-pixel max abs diff and compare with a tolerance that
    // absorbs float summation-order differences (additive accumulation).
    let mut max_diff = 0.0f32;
    let mut max_ref = 0.0f32;
    for (a, b) in ours.iter().zip(reference.iter()) {
        let d = (a - b).abs();
        if d > max_diff {
            max_diff = d;
        }
        if b.abs() > max_ref {
            max_ref = b.abs();
        }
    }
    println!("max |ours - r2| = {max_diff:.6}  (max |r2| = {max_ref:.6})");
    assert!(
        max_diff < 2.0e-4f32,
        "brush-xray forward deviates from R2-Gaussian by {max_diff}"
    );
}
